global:
  scrape_interval: 15s
  
rule_files:
  - rules.yaml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

{% if targets %}
{%for hosts in targets %}
  - job_name: '{{ hosts.name }}'
    scrape_interval: 5s
    static_configs:
      - targets: ['{{ hosts.url }}']
{% if hosts.username %}
    basic_auth:
      username: '{{ hosts.username }}'
      password: '{{ hosts.password }}'
{% endif %}
{% endfor %}
{% endif %}
