global:
  scrape_interval: 15s
  
rule_files:
  - rules.yaml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
      
<<<<<<< HEAD
 vim /etc/alertmanager/alertmanager.yml
 global:
  resolve_timeout: 5m
  slack_api_url: '{{ slack_webhook_url }}'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'DevOps'

receivers:
- name: 'DevOps'
  slack_configs:
  - channel: '#general'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
=======
>>>>>>> de185e575b070b9397365052e9c3418b081fae9a
