---
- hosts: monitoring
  become: true
  roles:
          - role: firewall
            tags: firewall
          - role: prometheus
            tags: prometheus
          - role: alertmanager
            tags: alertmanager
          - role: grafana
            tags: grafana
