global:
  resolve_timeout: 5m
{% if slack_webhook_url %}
  slack_api_url: '{{ slack_webhook_url }}'
{% endif %}

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'DevOps'

receivers:
- name: 'DevOps'
  slack_configs:
  - channel: '#general'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
