groups:
- name: Prometheus_Performance
  rules:
  - alert: Prometheus_Alertmanager_E2E_DeadManSwitch
    expr: vector(1)
    for: 0m
    labels:
      severity: none
      alertmanager: healthy
    annotations:
      description: "If you receive this message it means Alertmanager is working fine.\n        You should receive it every 30 minutes."

  - alert: Instance_Is_Down
    expr: up == 0
    for: 1m
    annotations:
      title: 'Instance {{ '{{' }} $labels.instance {{ '}}' }} down'
      description: '{{ '{{' }} $labels.instance {{ '}}' }} of job {{ '{{' }} $labels.job {{ '}}' }} has been down for more than 1 minute.'
    labels:
      severity: 'critical'

