---
- name: Disable swap
  shell:
          cmd: swapoff -a

- name: Edit /etc/fstab to disable swap permanently
  replace:
          path: /etc/fstab
          regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
          replace: '# \1'

- name: Edit /etc/hosts
  template:
          src: hosts
          dest: /etc/hosts

- name: Iptables bridge traffic
  template:
          src: k8s.conf
          dest: /etc/sysctl.d/

- name: Sysctl --system
  shell:
          cmd: sysctl --system

- name: Installing docker ( dependencies )
  apt:
          name:
                  - apt-transport-https
                  - ca-certificates
                  - curl
                  - gnupg
                  - lsb-release

- name: Installing docker ( add gpg key )
  shell:
          cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Installing docker ( add repository )
  shell:
          cmd: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Installing docker ( docker engine )
  apt:
          update_cache: yes
          name:
                  - docker-ce
                  - docker-ce-cli
                  - containerd.io
          state: present
